blank_issues_enabled: false
contact_links:
  - name: Propose a new feature
    url: https://github.com/nguyenhy/d11f/discussions/new?category=feature-proposal
    about: Share your ideas on how to expand this fork.
  - name: Ask a question or get help
    url: https://github.com/nguyenhy/d11f/discussions
    about: Engage with the community, ask questions, or help other developers.
